### ISSUE TITLE
Bounce handler idea

### ISSUE THREAD

**Issue by riaanp78** [muety/mailwhale#44] opened 2023-02-28 13:16 UTC
I have been thinking how you can implement a bounce handler quickly and safely.

With this article as reference: https://serverfault.com/questions/48326/how-to-collect-bounces-in-postfix

You could make a simple API endpoint that will wait for the mail server to send a bounce API request.

So the flow would look something like this:

postfix receives bounce -> bounce handler script processes the incoming mail bounce -> sends request via API to mailwhale with bounce info -> user is then informed etc 
Every email has a unique ID when sent. So it would be easy to track.

**Comment by muety** [comment] 2023-03-01 08:36
I see, but this would require to hook in a script into Postfix, no? MailWhale is meant to work with any (third-party) SMTP provider (such as GMail), where you wouldn't have access to the underlying infrastructure.

**Comment by riaanp78** [comment] 2023-03-01 08:40
ahh yes. I forgot about that. never mind then. then your idea to read from the IMAP mailbox is much much better

**Comment by muety** [comment] 2023-03-01 08:41
Thanks for your thoughts anyway!

Closed as duplicate of #4.

**Closed by muety** 2023-03-01 08:41 UTC
